# Generated by Django 5.0.9 on 2024-11-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
    ]
