# Generated by Django 5.0.9 on 2024-11-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAluno', models.IntegerField()),
                ('data', models.DateField()),
                ('horas_prestadas', models.IntegerField()),
                ('local', models.CharField(max_length=255)),
                ('supervisor', models.CharField(max_length=255)),
                ('comprovante', models.BinaryField(max_length='max')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
