# Generated by Django 5.0.9 on 2024-11-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprovantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteComentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Aprovado'), (2, 'Rejeitado')])),
                ('id_comprovante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comprovantes.comprovante')),
            ],
        ),
    ]
