# Generated by Django 5.0.9 on 2024-11-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprovantes', '0004_alter_comprovante_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprovantecomentario',
            old_name='comentario',
            new_name='texto',
        ),
    ]
